# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.TextField()),
                ('idFlux', models.TextField()),
                ('order_id', models.TextField()),
                ('order_mrid', models.TextField()),
                ('order_refid', models.TextField()),
            ],
        ),
    ]
